apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: <namespace>
spec:
  serviceName: "elasticsearch"
  selector:
    matchLabels:
      app: elasticsearch
  replicas: 1 
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:   
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "app"
        effect: "NoSchedule"
      initContainers:
      - image: stakater/elasticsearch-restore:0.0.10
        name: elasticsearch-restore-init
        env:
        - name: VOLUME
          value: "/usr/share/elasticsearch/data"
        - name: S3_BUCKET_NAME
          valueFrom:
            secretKeyRef:
              name: <k8s-secret-name>
              key: es_bucket
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: <k8s-secret-name>
              key: aws_access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: <k8s-secret-name>
              key: aws_secret_access_key
        - name: AWS_DEFAULT_REGION
          valueFrom:
            secretKeyRef:
              name: <k8s-secret-name>
              key: aws_default_region
        - name: RESTORE
          value: "false"
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: elasticsearch-pvc-1
          
      containers:
      - image: stakater/elasticsearch:2.3.1
        name: elasticsearch
        env:  
        - name: discovery.type
          value: "single-node"
        - name: bootstrap.memory_lock
          value: "true"
        - name: ES_JAVA_OPTS
          value: "-Xms512m -Xmx512m"
        ports:
        - containerPort: 9200
          name: tcp
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: elasticsearch-pvc-1
        resources: {}      

      - image: stakater/elasticsearch-backup:0.0.10
        name: elasticsearch-backup
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: elasticsearch-pvc-1
        env:
        - name: CRON_TIME
          value: "00 */1 * * *"
        - name: VOLUME
          value: "/usr/share/elasticsearch/data"
        - name: S3_BUCKET_NAME
          valueFrom:
            secretKeyRef:
              name: <k8s-secret-name>
              key: es_bucket
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: <k8s-secret-name>
              key: aws_access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: <k8s-secret-name>
              key: aws_secret_access_key
        - name: AWS_DEFAULT_REGION
          valueFrom:
            secretKeyRef:
              name: <k8s-secret-name>
              key: aws_default_region
          
  volumeClaimTemplates:
  - metadata:
      name: elasticsearch-pvc-1
    spec:
      accessModes: [ "ReadWriteMany" ]
      storageClassName: efs
      resources:
        requests:
          storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: elasticsearch-svc
  name: elasticsearch-svc
  namespace: <namespace>
spec:
  ports:
  - name: "es-port"
    port: 9300
    targetPort: 9300
  - name: "es-port-2"
    port: 9200
    targetPort: 9200
  selector:
    app: elasticsearch